
filelist:
	@echo "# Pulpissimo SystemVerilog filelist for Yosys" > pulpissimo.f
	@echo "# Generated by: make -f vcompile/rtl/pulpissimo.mk filelist" >> pulpissimo.f
	@echo "# Usage: yosys -p 'read_verilog -sv @pulpissimo.f $(YOSYS_INCDIR_PULPISSIMO); ...'" >> pulpissimo.f
	@for file in $(SRC_SVLOG_PULPISSIMO); do \
		echo $$file >> pulpissimo.f; \
	done
	@echo "" >> pulpissimo.f
	@echo "# Include directory (use with -I flag):" >> pulpissimo.f
	@echo "$(YOSYS_INCDIR_PULPISSIMO)" >> pulpissimo.f
	@echo "Filelist generated: pulpissimo.f"